# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon("icon.jpg"))
        MainWindow.resize(888, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_account = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_account.setGeometry(QtCore.QRect(0, 10, 881, 591))
        self.tab_account.setObjectName("tab_account")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.list_account_ac = QtWidgets.QListWidget(parent=self.Account)
        self.list_account_ac.setGeometry(QtCore.QRect(670, 50, 191, 431))
        self.list_account_ac.setObjectName("list_account_ac")
        self.add_account = QtWidgets.QPushButton(parent=self.Account)
        self.add_account.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.add_account.setObjectName("add_account")
        self.account_input_add = QtWidgets.QLineEdit(parent=self.Account)
        self.account_input_add.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.account_input_add.setObjectName("account_input_add")
        self.remove_account_input = QtWidgets.QLineEdit(parent=self.Account)
        self.remove_account_input.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.remove_account_input.setObjectName("remove_account_input")
        self.remove_account_bot = QtWidgets.QPushButton(parent=self.Account)
        self.remove_account_bot.setGeometry(QtCore.QRect(200, 70, 101, 31))
        self.remove_account_bot.setObjectName("remove_account_bot")
        self.help_account_add = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_account_add.setGeometry(QtCore.QRect(310, 20, 341, 31))
        self.help_account_add.setObjectName("help_account_add")
        self.help_remove_account = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_remove_account.setGeometry(QtCore.QRect(310, 70, 341, 41))
        self.help_remove_account.setObjectName("help_remove_account")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.Account)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 20, 111, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.Account)
        self.lcdNumber.setGeometry(QtCore.QRect(690, 490, 151, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.update_number_bot = QtWidgets.QPushButton(parent=self.Account)
        self.update_number_bot.setGeometry(QtCore.QRect(570, 500, 111, 41))
        self.update_number_bot.setObjectName("update_number_bot")
        self.tab_account.addTab(self.Account, "")
        self.Extract = QtWidgets.QWidget()
        self.Extract.setObjectName("Extract")
        self.group_extracct_input = QtWidgets.QLineEdit(parent=self.Extract)
        self.group_extracct_input.setGeometry(QtCore.QRect(20, 20, 301, 31))
        self.group_extracct_input.setText("")
        self.group_extracct_input.setObjectName("group_extracct_input")
        self.extract_bot = QtWidgets.QPushButton(parent=self.Extract)
        self.extract_bot.setGeometry(QtCore.QRect(340, 20, 131, 31))
        self.extract_bot.setObjectName("extract_bot")
        self.lcdNumber_member_extract = QtWidgets.QLCDNumber(parent=self.Extract)
        self.lcdNumber_member_extract.setGeometry(QtCore.QRect(500, 60, 161, 81))
        self.lcdNumber_member_extract.setObjectName("lcdNumber_member_extract")
        self.list_ex = QtWidgets.QListWidget(parent=self.Extract)
        self.list_ex.setGeometry(QtCore.QRect(20, 120, 301, 431))
        self.list_ex.setObjectName("list_ex")
        self.stop_extract = QtWidgets.QPushButton(parent=self.Extract)
        self.stop_extract.setGeometry(QtCore.QRect(510, 20, 131, 31))
        self.stop_extract.setObjectName("stop_extract")
        self.status_extract = QtWidgets.QTextBrowser(parent=self.Extract)
        self.status_extract.setGeometry(QtCore.QRect(330, 60, 161, 31))
        self.status_extract.setObjectName("status_extract")
        self.list_group_rem = QtWidgets.QComboBox(parent=self.Extract)
        self.list_group_rem.setGeometry(QtCore.QRect(340, 160, 231, 31))
        self.list_group_rem.setObjectName("list_group_rem")
        self.rem_extract_bot = QtWidgets.QPushButton(parent=self.Extract)
        self.rem_extract_bot.setGeometry(QtCore.QRect(390, 200, 131, 51))
        self.rem_extract_bot.setObjectName("rem_extract_bot")
        self.help_ex_link = QtWidgets.QTextBrowser(parent=self.Extract)
        self.help_ex_link.setGeometry(QtCore.QRect(20, 60, 301, 41))
        self.help_ex_link.setObjectName("help_ex_link")
        self.log_extract = QtWidgets.QPlainTextEdit(parent=self.Extract)
        self.log_extract.setGeometry(QtCore.QRect(340, 330, 521, 211))
        self.log_extract.setObjectName("log_extract")
        self.tab_account.addTab(self.Extract, "")
        self.Adder = QtWidgets.QWidget()
        self.Adder.setObjectName("Adder")
        self.list_group_load = QtWidgets.QComboBox(parent=self.Adder)
        self.list_group_load.setGeometry(QtCore.QRect(20, 20, 261, 31))
        self.list_group_load.setObjectName("list_group_load")
        self.load_member_bot = QtWidgets.QPushButton(parent=self.Adder)
        self.load_member_bot.setGeometry(QtCore.QRect(290, 20, 111, 31))
        self.load_member_bot.setObjectName("load_member_bot")
        self.lcdNumber_load = QtWidgets.QLCDNumber(parent=self.Adder)
        self.lcdNumber_load.setGeometry(QtCore.QRect(170, 60, 101, 51))
        self.lcdNumber_load.setObjectName("lcdNumber_load")
        self.numberuser_text = QtWidgets.QTextBrowser(parent=self.Adder)
        self.numberuser_text.setGeometry(QtCore.QRect(20, 70, 141, 31))
        self.numberuser_text.setObjectName("numberuser_text")
        self.input_link_add = QtWidgets.QLineEdit(parent=self.Adder)
        self.input_link_add.setGeometry(QtCore.QRect(400, 120, 221, 31))
        self.input_link_add.setText("")
        self.input_link_add.setObjectName("input_link_add")
        self.text_add_link = QtWidgets.QTextBrowser(parent=self.Adder)
        self.text_add_link.setGeometry(QtCore.QRect(10, 120, 381, 31))
        self.text_add_link.setObjectName("text_add_link")
        self.clear_load_bot = QtWidgets.QPushButton(parent=self.Adder)
        self.clear_load_bot.setGeometry(QtCore.QRect(290, 70, 111, 31))
        self.clear_load_bot.setObjectName("clear_load_bot")
        self.text_add_num = QtWidgets.QTextBrowser(parent=self.Adder)
        self.text_add_num.setGeometry(QtCore.QRect(10, 160, 371, 31))
        self.text_add_num.setObjectName("text_add_num")
        self.text_add_num_2 = QtWidgets.QTextBrowser(parent=self.Adder)
        self.text_add_num_2.setGeometry(QtCore.QRect(10, 200, 371, 31))
        self.text_add_num_2.setObjectName("text_add_num_2")
        self.number_add_bot = QtWidgets.QSpinBox(parent=self.Adder)
        self.number_add_bot.setGeometry(QtCore.QRect(390, 160, 61, 31))
        self.number_add_bot.setObjectName("number_add_bot")
        self.number_acc_add = QtWidgets.QSpinBox(parent=self.Adder)
        self.number_acc_add.setGeometry(QtCore.QRect(390, 200, 61, 31))
        self.number_acc_add.setObjectName("number_acc_add")
        self.log_adder = QtWidgets.QPlainTextEdit(parent=self.Adder)
        self.log_adder.setGeometry(QtCore.QRect(10, 360, 861, 181))
        self.log_adder.setObjectName("log_adder")
        self.ok_number = QtWidgets.QLCDNumber(parent=self.Adder)
        self.ok_number.setGeometry(QtCore.QRect(200, 240, 101, 51))
        self.ok_number.setObjectName("ok_number")
        self.start_adder_bot = QtWidgets.QPushButton(parent=self.Adder)
        self.start_adder_bot.setGeometry(QtCore.QRect(470, 170, 121, 51))
        self.start_adder_bot.setObjectName("start_adder_bot")
        self.bad_number = QtWidgets.QLCDNumber(parent=self.Adder)
        self.bad_number.setGeometry(QtCore.QRect(200, 300, 101, 51))
        self.bad_number.setObjectName("bad_number")
        self.number_text_successful = QtWidgets.QTextBrowser(parent=self.Adder)
        self.number_text_successful.setGeometry(QtCore.QRect(10, 250, 181, 31))
        self.number_text_successful.setObjectName("number_text_successful")
        self.number_text_unsuccessful = QtWidgets.QTextBrowser(parent=self.Adder)
        self.number_text_unsuccessful.setGeometry(QtCore.QRect(10, 320, 181, 31))
        self.number_text_unsuccessful.setObjectName("number_text_unsuccessful")
        self.stop_adder_bot = QtWidgets.QPushButton(parent=self.Adder)
        self.stop_adder_bot.setGeometry(QtCore.QRect(600, 170, 121, 51))
        self.stop_adder_bot.setObjectName("stop_adder_bot")
        self.update_list_gaps = QtWidgets.QPushButton(parent=self.Adder)
        self.update_list_gaps.setGeometry(QtCore.QRect(410, 20, 111, 31))
        self.update_list_gaps.setObjectName("update_list_gaps")
        self.save_log_bot = QtWidgets.QPushButton(parent=self.Adder)
        self.save_log_bot.setGeometry(QtCore.QRect(790, 330, 75, 23))
        self.save_log_bot.setObjectName("save_log_bot")
        self.acc_complate_number = QtWidgets.QLCDNumber(parent=self.Adder)
        self.acc_complate_number.setGeometry(QtCore.QRect(560, 240, 101, 51))
        self.acc_complate_number.setObjectName("acc_complate_number")
        self.number_accs_successful = QtWidgets.QTextBrowser(parent=self.Adder)
        self.number_accs_successful.setGeometry(QtCore.QRect(330, 250, 221, 31))
        self.number_accs_successful.setObjectName("number_accs_successful")
        self.tab_account.addTab(self.Adder, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_account.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Channel Member Adder 2025 By https://erfan4lx.com"))
        self.add_account.setText(_translate("MainWindow", "Add account"))
        self.account_input_add.setText(_translate("MainWindow", "+123456789"))
        self.remove_account_input.setText(_translate("MainWindow", "+123456789"))
        self.remove_account_bot.setText(_translate("MainWindow", "Remove account"))
        self.help_account_add.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">This section is for adding an account.</span></p></body></html>"))
        self.help_remove_account.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">This section is for deleting an existing account in the program.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">List Accounts</span></p></body></html>"))
        self.update_number_bot.setText(_translate("MainWindow", "Update Number"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Account), _translate("MainWindow", "Account"))
        self.extract_bot.setText(_translate("MainWindow", "Extracting members"))
        self.stop_extract.setText(_translate("MainWindow", "Stop Extract"))
        self.status_extract.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Status : Disactive</span></p></body></html>"))
        self.rem_extract_bot.setText(_translate("MainWindow", "Remove Gap Extract"))
        self.help_ex_link.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">link : @group | t.me/+Smxcjsiw28cx</span></p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Extract), _translate("MainWindow", "Extract"))
        self.load_member_bot.setText(_translate("MainWindow", "Load Members"))
        self.numberuser_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Number User Load :</span></p></body></html>"))
        self.text_add_link.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ChatID channel to ADD : (max 200 members) [-100123456789]</span></p></body></html>"))
        self.clear_load_bot.setText(_translate("MainWindow", "Clear Load"))
        self.text_add_num.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Number of ADDs per account:</span></p></body></html>"))
        self.text_add_num_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Number of accounts for operations:</span></p></body></html>"))
        self.start_adder_bot.setText(_translate("MainWindow", "Start Adder"))
        self.number_text_successful.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Number of successful:</span></p></body></html>"))
        self.number_text_unsuccessful.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Number of unsuccessful:</span></p></body></html>"))
        self.stop_adder_bot.setText(_translate("MainWindow", "Stop Adder"))
        self.update_list_gaps.setText(_translate("MainWindow", "update list"))
        self.save_log_bot.setText(_translate("MainWindow", "save log"))
        self.number_accs_successful.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Number of completed accounts:</span></p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Adder), _translate("MainWindow", "Adder"))
